# ═══════════════════════════════════════════════════════════════════
# Render Deployment Config (DEPRECATED)
# ═══════════════════════════════════════════════════════════════════
# We've migrated to Railway.app for better reliability.
# See railway.json for the current deployment configuration.
# ═══════════════════════════════════════════════════════════════════
